
name: Vercel Deployment

on:
  workflow_dispatch:
    inputs:
      vercel-token:
        description: 'Vercel API Token'
        required: true
        type: string
      vercel-org-id:
        description: 'Vercel Organization ID'
        required: true
        type: string
      vercel-project-id:
        description: 'Vercel Project ID'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        env:
          VERCEL_TOKEN: ${{ inputs.vercel-token }}
          VERCEL_ORG_ID: ${{ inputs.vercel-org-id }}
          VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

